export default {
    LOGIN: 'Login',
    TAB_BAR_PROPERTIES: 'Properties',
    TAB_BAR_USERS: 'Surf Leads',
    TAB_BAR_CONTACTS: 'Contacts',
    TAB_BAR_DASHBOARD: 'Dashboard',
    TRANSACTION_DESK: 'Transaction Desk',
    TAB_BAR_MESSAGE: 'Messages',
    TAB_BAR_CHAT: 'Chat',
    TAB_BAR_CALL: 'Call',
    AGENTS: "Agents",
    RETALORS: 'Retalors',
    CALL_CENTER: "Call Center",
    USER_PROFILE: 'User Profile',
    CONTACT_VIEW: 'Contact',
    DOCUMENT_PORTAL: 'Document Portal',
    DOCUMENT_PORTAL_DETAIL: 'Document Portal Detail',
    MARKETING: 'Marketing',
    SELF_SOURCED_LEADS: 'Self Sourced Leads'
};